Repository codemistic/HacktoberFest, pull requests merged in 2022-09, with the labels that each got.

#3 Added some non code projects
  README.md
Labels: documentation, enhancement, good first issue, Hacktoberfest

#17 Create cricket.py
  General-Projects/cricket.py
Labels: enhancement, Hacktoberfest

#24 updated README.md
  README.md
Labels: Hacktoberfest

#25 Create The-Skyline-Problem.cpp
  CPP/The-Skyline-Problem.cpp
Labels: Hacktoberfest, hacktoberfest-accepted
